# OCR Configuration
ocr:
  read_interval: 1.0
  confidence_threshold: 0.8
  regions_file: 'config/ocr_regions.json'
  default_atr: 10.0

# Kelly Criterion Engine
kelly:
  history_length: 100
  base_win_rate: 0.5
  kelly_fraction: 0.5
  min_trades_for_dynamic: 10
  max_position_pct: 0.02
  initial_balance: 50000
  min_balance: 25000
  drawdown_reduction_factor: 0.5

# ATR Risk Management
atr:
  atr_period: 14
  sl_multiplier: 1.5
  pt_multiplier: 2.0
  default_atr: 10.0
  max_price_history: 1000

# Enigma Cadence Tracking
cadence:
  am_threshold: 2
  pm_threshold: 3
  max_history: 1000

# Apex Prop Firm Compliance
apex:
  account_size: 50000
  max_daily_loss: 2000
  max_trailing_loss: 3000
  profit_target: 3000
  max_contracts: 10
  max_position_value: 50000
  consistency_threshold: 0.4
  monitor_interval: 5.0

# NinjaTrader Integration
ninjatrader:
  websocket_host: 'localhost'
  websocket_port: 8080
  reconnect_delay: 5.0
  heartbeat_interval: 30.0

# Mobile API
mobile:
  api_host: '0.0.0.0'
  api_port: 8000
  auth_token: 'change_this_token'
  ssl_enabled: false

# Risk Management
risk:
  monitor_interval: 1.0
  emergency_stop_enabled: true
  max_daily_trades: 20

# Signal Filters
filters:
  min_power: 15
  required_confluence: ['L3', 'L4']
  macvu_required: true

# Logging
logging:
  level: 'INFO'
  max_file_size: 10485760
  backup_count: 5
